- micromanager_gui/_core/_client.py
- micromanager_gui/_core/_pyrocore.py
- micromanager_gui/_core/_server.py
- micromanager_gui/_ui/micromanager_gui.ui
- micromanager_gui/main_window.py
- micromanager_gui/multid_widget.py
convert main window to Qwidget ... other cleanup
> cleanup detatched core connection properly, cleanup main widget

- .github/workflows/test.yml
- micromanager_gui/_util.py
- micromanager_gui/install_mm.py
- micromanager_gui/main_window.py
- setup.cfg
- tests/test_main_window.py
reduce code in on_mda_frame, no explicit axis requirements
this PR also fixes tests and drops support for python 3.7 (which doesn't have the shared memory support we want to use).
> minimize on_mda_frame, fix tests, drop 3.7

- micromanager_gui/main_window.py
- micromanager_gui/multid_widget.py
- setup.cfg
Following: https://github.com/tlambert03/pymmcore-plus/issues/9
> rename pymmcore-remote to pymmcore-plus

- setup.cfg
- tests/test_main_window.py
Accounting for changes to the remote server management in https://github.com/tlambert03/pymmcore-plus/pull/47
> update tests for newest pymmcore-plus

- micromanager_gui/multid_widget.py
Fix #100 
from bool: `self.checkBox_save_pos.setCheckState(False)`
to: `self.checkBox_save_pos.setCheckState(Qt.CheckState.Unchecked)`
> fix setCheckState in mda using Qt.CheckState

- micromanager_gui/_ui/micromanager_gui.ui
- micromanager_gui/main_window.py
1. Fix loading of demo config
2. Switch to using placeholder text
3. Fix capitalization of `MIcro` to `Micro`
*main:*
notably it also fails load given the changes in pymmc+
This PR:
> Updates to config lineedit

- setup.cfg
> add tifffile requirement

- micromanager_gui/_camera_roi.py
- micromanager_gui/explore_sample.py
- micromanager_gui/main_window.py
- micromanager_gui/multid_widget.py
- setup.cfg
- tests/conftest.py
- tests/test_main_window.py
Is it ok to just relying on the old tests for now? I'd like to add more once the mda widgets get a bit cleaned up as discussed in #130
> update for new pymmcore-plus mda

- micromanager_gui/_util.py
- micromanager_gui/main_window.py
two of these were non-functional and `blockSignals` should be superceded by the version in superqt
> cleanup utils

- micromanager_gui/_gui_objects/_sample_explorer_widget.py
- micromanager_gui/main_window.py
- `self._mmc.cancel()` -> `self._mmc._mda_engine.cancel()`
- `self.viewer.layers.remove("preview")` on explorer start
> minor explorer fix/update

- micromanager_gui/_gui_objects/_mm_widget.py
Simply setting the vertical `sizePolicy` to `Fixed` solved the problem.
`coll_sizepolicy = QtW.QSizePolicy(QtW.QSizePolicy.Minimum, QtW.QSizePolicy.Fixed)`
> easy fix to the stage collapsible that is not closing properly

- .pre-commit-config.yaml
- micromanager_gui/__init__.py
- micromanager_gui/_camera_roi.py
- micromanager_gui/_core.py
- micromanager_gui/_core_widgets/__init__.py
- micromanager_gui/_core_widgets/_device_widget.py
- micromanager_gui/_core_widgets/_exposure_widget.py
- micromanager_gui/_core_widgets/_live_button_widget.py
- micromanager_gui/_core_widgets/_presets_widget.py
- micromanager_gui/_core_widgets/_property_browser.py
- micromanager_gui/_core_widgets/_property_widget.py
- micromanager_gui/_core_widgets/_stage_widget.py
- micromanager_gui/_gui_objects/_group_preset_table_widget.py
- micromanager_gui/_gui_objects/_mda_widget/_mda_gui.py
- micromanager_gui/_gui_objects/_mda_widget/_mda_widget.py
- micromanager_gui/_gui_objects/_mm_widget.py
- micromanager_gui/_gui_objects/_objective_widget.py
- micromanager_gui/_gui_objects/_sample_explorer_widget/_sample_explorer_gui.py
- micromanager_gui/_gui_objects/_sample_explorer_widget/_sample_explorer_widget.py
- micromanager_gui/_gui_objects/_shutters_widget.py
- micromanager_gui/_gui_objects/_tab_widget.py
- micromanager_gui/_gui_objects/_xyz_stages.py
- micromanager_gui/_mda.py
- micromanager_gui/_saving.py
- micromanager_gui/_util.py
- micromanager_gui/main_window.py
- setup.cfg
- tests/core_widgets/test_presets_widget.py
This PR may be slightly annoying, but let's try it :) This adds flake8 docstrings, (with a lax policy not forcing all public methods to be documented...) but generally imposing some structure to our docstrings).  It catches both formatting inconsistencies, as well as things like missing parameters in docstrings
> docs: big flake8 docstring update

- .pre-commit-config.yaml
- micromanager_gui/_camera_roi.py
- micromanager_gui/_core_widgets/_live_button_widget.py
- micromanager_gui/_core_widgets/_presets_widget.py
- micromanager_gui/_core_widgets/_property_browser.py
- micromanager_gui/_core_widgets/_property_widget.py
- micromanager_gui/_gui_objects/_channel_widget.py
- micromanager_gui/_gui_objects/_mda_widget/_mda_widget.py
- micromanager_gui/_gui_objects/_sample_explorer_widget/_sample_explorer_widget.py
- micromanager_gui/_gui_objects/_slider_dialog.py
- micromanager_gui/_mda.py
- micromanager_gui/_saving.py
- micromanager_gui/_util.py
- micromanager_gui/main_window.py
- pyproject.toml
- tests/test_explorer.py
This one is probably even more important #175 , it adds basic mypy checking to the pre-commit checks.  It's not in "strict" mode, so it's still pretty lax, but turning it on revealed a number of latent bugs (and a few warnings, that just needed to be manually ignored).
It's a good practice to get into to have it on all the time :) so let's try it out
> ci: add mypy to pre-commit checks

- micromanager_gui/main_window.py
Small PR to solve broken live mode.
> fix: Fix Live mode (#127)

- micromanager_gui/_gui_objects/_mda_widget/_mda_gui.py
I think this is generally preferable? At the very least it's what I prefer and I'm finding myself constantly switching it.
> feat: set `tpcz` as default MDA order

- .github/dependabot.yml
- .github/workflows/test.yml
see if we can remove ` -r 20220420` from tests
> test: unpin micrmanager device version in tests

- src/napari_micromanager/_gui_objects/_sample_explorer_widget.py
- tests/test_explorer.py
This PR fixes the Explorer widget and the tests.
> fix: update explorer + fix tests

- tests/test_explorer.py
Changes upstream were breaking things here: e.g.
https://github.com/pymmcore-plus/napari-micromanager/actions/runs/4788665546/jobs/8515572204
> test: update explorer tests to unbreak them

- README.md
> docs: Update README.md with new image

- .github/workflows/ci.yml
- README.md
- src/napari_micromanager/_mda_handler.py
- tests/test_multid_widget.py
> fix: fix rgb MDA
