micromanager_gui/_ui/micromanager_gui.ui, micromanager_gui/main_window.py
Previously if you also had a separate client to `pymmcore-remote` that changed the exposure then the gui would not update and then would overwrite the  value.
There is a similar issue with `channels` (perhaps config groups generally) but I'm struggling with figuring out the `gets` and sets`. I would open an issue about this by it seems that issues are disabled on this repo currently.
=> Allow exposure to be a float + connect to exposure changed signal

README.md, launch-dev.py, micromanager_gui/main_window.py
This PR adds two things
1. The development helper script from #27 and added a brief description to the readme.
2. bi-directional callbacks for when the channel is changed (also use the channelGroup when possible)
Closes: https://github.com/tlambert03/napari-micromanager/issues/26
Gets at part of #21, I didn't use the declarative mapping here because I think that this is the only config group that currently has an effect on the GUI. However, your proposed mapping will be helpful for the device properties.
=> Add callbacks to deal with setting channel

.github/workflows/test.yml
Should hopefully significantly speed up the tests as the install step is taking most of the time:
=> add pip caching to github actions

micromanager_gui/main_window.py
This makes the display significantly less laggy when moving the stage around. Inspired by MMs implementation.
Inspired by https://github.com/micro-manager/micro-manager/blob/4a5d51ea76f89eaa6e74d0d772822701661aa76a/mmstudio/src/main/java/org/micromanager/internal/SnapLiveManager.java#L406
=> Use `getLastImage` for live mode

micromanager_gui/explore_sample.py
`f{"None:.1f}"` throws an error and this should protect against that. Also Ideally sets the drag callback to do it's work if the explore sample widget is currently visible (Is there a way to fully disable the callback rather than returning early?) 
Attn: @fdrgsp
=> Protect against string formatting None

micromanager_gui/main_window.py
1. Autofill the z_line-edit when config loaded - otherwise it only updated once you moved the z stage
2. Don't snap when clicking the z up/down buttons (This feels like the correct behavior to me, otherwise you end up stopping live mode if you are already in it.)
=> Small z-position fixes

micromanager_gui/main_window.py
Now that the callbacks on the GUI are all hooked up snap no longer needs to do expensive things like setting the config group. Also rather than stopping live mode to snap we should disable the ability to snap when live mode is on.
=> simplify snap

micromanager_gui/multid_widget.py
replace focus device label with `getFocusDevice()` in `move_to_position()` method (multid_widget.py).
The move_to_position function (when you double-click on one of the recorded positions in the mda positions table) will now use as "z stage" the device that is set as main focus device.
=> replace focus device label with getFocusDevice() 

micromanager_gui/_util.py, micromanager_gui/main_window.py, micromanager_gui/multid_widget.py
Follow up to https://github.com/tlambert03/napari-micromanager/pull/54
Also:
- Expanded the functionality of `blockSignals` to take a list of widgets.
- Be more careful when loading a config that we don't accidentally set properties when `clear`ing the spinboxes
=> Use new `getChannelGroup getter from pymmc+

micromanager_gui/_util.py, micromanager_gui/explore_sample.py, micromanager_gui/main_window.py, micromanager_gui/multid_widget.py, setup.cfg
As explained in [tlambert03/pymmcore-plus/PR#67](https://github.com/tlambert03/pymmcore-plus/pull/67), the new `getOrGuessChannelGroup()` method from `pymmcore-plus` will return a `list` instead of a single string. As for the objective device (#43):
- `_refresh_channel_list()` -> it uses the `getOrGuessChannelGroup()` method in `pymmcore-plus` to get a list of possible channel group configurations.
- If there is only one element in the list (only 1 possible guessed channel group configuration), then the channel group is set through the new `_set_channel_group()` method.
- If there are more elements in the list, it lets you chose the correct guessed channel group configuration through a magicgui combobox (`SelectDeviceFromCombobox()` class in `_util.py`)
=> set channel group using new getOrGuessChannelGroup() method from pymmcore-plus

micromanager_gui/main_window.py
Use a thread when snapping to prevent the UI freezing when using `CMMCorePlus`.
I tried to use the napari generator threading example to only need to spawn one worker, but I couldn't consistently get it to not accidentally snap twice so spawning a new one everytime (unless this is a bad thing?)
I also tried to add the option of psasing and existing core object in to allow launching napari from another script and still having access to the core object (aside from `main_window._mmc` but I think that this is limited by https://github.com/napari/napari/issues/1211. So maybe it would be good for the process local pymmcore-plus to have a mechanism to get an already existing CMMCore object if one exists?
The other issue I'm noticing that probably will need fixing on pymmcore-plus is that now …
=> use threads for snap

micromanager_gui/explore_sample.py
Reset the napari viewer `zoom` and `view` every time a frame is acquired when using `explore_sample.py'.
https://user-images.githubusercontent.com/70725613/155626791-f0798251-57c4-4418-96ee-36aead71d641.mov
=> napari reset view in explorer

micromanager_gui/main_window.py
Fixes #113 
This one decorator (a brilliant contribution to superqt from @czaki) is all that was needed to fix the errors that happen when the `CMMCore.events` object is backed by `psygnal.Signal` instead of `QtCore.Signal`.
Some notes on how I debugged this:
1. I ran the script provided in #113 using `NAPARI_DEBUG_EVENTS=1 python script.py`
2. that showed that it was consistently the `viewer.add_image()` call in `_on_mda_frame` that caused the crash:
```py
LayerList.events.inserting(index=0)
was triggered by Viewer.add_image(), via:
".../site-packages/napari/utils/events/containers/_evented_list.py", line 177, in LayerList.insert
".../site-packages/napari/utils/events/containers/_selectable_list.py", line 65, in LayerList.insert
".../site-packages/napari/components/layerlist.py", line …
```
=> Ensure `_on_mda_frame` is called in main thread

codecov.yml, micromanager_gui/_gui_objects/_device_widget.py, setup.cfg, tests/test_device_widget.py
a start on creating more generic widgets that work for given device types.
This establishes new base class `DeviceWidget` that accepts the name of a device and is expected to make widget that controls the device.  In most cases, it will be created with the classmethod `DeviceWidget.for_device('deviceLabel')` which creates the appropriate subclass.  Here, `StateDevice` is implemented... but `for_device` will raise a NotImplementedError for all other device types (to be implemented later).
=> Generic device widget, and StateDeviceWidget

tests/conftest.py
Previously we were always getting the same core instance for each test due to the instancing of `CMMCorePlus.instance()`
this fixes that, and then fixes the test that then broke (which is also whats breaking #134 )
Pulling out of that to make things simpler to review
=> Ensure a new Core instance for each test

launch-dev.py, micromanager_gui/_gui_objects/_mda_widget.py, micromanager_gui/_gui_objects/_mm_widget.py, micromanager_gui/_gui_objects/_sample_explorer_widget.py, micromanager_gui/_mda.py, micromanager_gui/_saving.py, micromanager_gui/explore_sample.py, micromanager_gui/main_window.py, tests/conftest.py, tests/test_explorer.py, tests/test_main_window.py, tests/test_multid_widget.py
Building on #132 
Prior to this PR there was some complex coupling between the multi_d widget, the explore sample widget and the main window. The aim here is to simplify and break that up. My goals are:
1.  `explore_sample` and `mda_widget` do not have to know anything about napari  or eachother
- They are each responsible only for constructing the appropriate MDASequence and  pause/stop
2. All interactions with Napari are confined to main_window widget
3. we also support displaying MDAs that initiated outside of napari-micromanager
(Partially done - but didn't want to lose this description that I wrote)
=> Begin cleanup and decoupling of mda

setup.cfg
I don't think scikit-image is being used anywhere
=> dependencies: update pymmc+ and remove scikit-image

setup.cfg
Perhaps fixes #153  ... let's see.
The warning coming from napari was causing a fail here, due to test settings
=> Only fail tests on internal warnings

.github/workflows/test.yml
see https://stackoverflow.com/questions/70663523/the-unauthenticated-git-protocol-on-port-9418-is-no-longer-supported
should hopefully fix the failing windows tests
Example failure from https://github.com/tlambert03/napari-micromanager/runs/5592092388?check_suite_focus=true
=> update opengl git url

micromanager_gui/_core_widgets/__init__.py, micromanager_gui/_core_widgets/_exposure_widget.py, micromanager_gui/_gui_objects/_tab_widget.py, micromanager_gui/main_window.py, tests/core_widgets/test_exposure_widget.py
Adds two new core widgets:
1. A general exposure widget that takes any camera neame
2. an exposure widget that follows the current camera device (`getCameraDevice`) as closely as possible. Though not perfectly, see https://github.com/micro-manager/mmCoreAndDevices/issues/181
There's also a bugfix in here. Previously if you loaded a config before opening napari then the exposure widget would not fill with the correct value - now it does.
=> create ExposureWidget as a core  widget + properly connect exposure signals

micromanager_gui/_gui_objects/_tab_widget.py
minor fix of how the DefaultCameraExposureWidget (and the channel widget) are displayed. Setting the `SizePolicy` fixed this issue
=> fix DefaultCameraExposureWidget widgets layout

micromanager_gui/_core_widgets/_presets_widget.py
I think it can be useful to know all the `properties` that have been assigned to a `group/preset` without using a "future" edit button/menu (we don't have it yet but I want to add it at some point) like in micromanager. 
This PR just adds `ToolTip` info depending on the `group-preset` `mmcore` `getConfigData()`.
It will work as in the examples below:
=> add ToolTip to any preset widget

.github/workflows/test.yml
Release failed due to this https://github.com/tlambert03/napari-micromanager/runs/6515242667?check_suite_focus=true
attn: @tlambert03
=> use build instead of setup.py

micromanager_gui/_core_widgets/_live_button_widget.py, micromanager_gui/_core_widgets/_snap_button_widget.py
Previously if you accidently loaded the demo config before loading a real one then the `snap` button would fail because `self._camera` was not being updated. This does remove the ability to pass in a user chosen camera, but I don't think that that's very useful because both `snap` and `startContinuousSequenceAcquisition` don't actually take camera arguments.
=> fix: always track the current camera for live and snap buttons

setup.cfg
This got missed in https://github.com/pymmcore-plus/napari-micromanager/pull/145
=> fix: Make zarr a requirement

micromanager_gui/main_window.py
fix `self._prop_browser` args: `(self._mmc, self)` -> `(mmcore=self._mmc, parent=self)`
=> fix: fix self._prop_browser args

pyproject.toml, src/napari_micromanager/__main__.py, tests/test_main.py
adds a `napari-micromanager` command (same as `python -m napari_micromanager`)
=> feat: add napari-micromanager command prompt

src/napari_micromanager/_gui_objects/_shutters_widget.py, src/napari_micromanager/main_window.py, tests/test_main_window.py
Mostly just puts all connections to external objects in one clear place.  Also adds a smoke test for the main window.
@fdrgsp ... I did find one problem, and that is the `empty_shutter = ShuttersWidget("")` that you add to the layout.  I don't think the pymmcore-widgets `ShuttersWidget` is ready for any random string (it isn't tested for it at least) ... it generally seems to assume that it's going to get a valid device label.  I found that it would raise an error in certain cases if you create a MainWindow _without_ already having had loaded a system configuration.  And even if you load one later... it's too late, the broken shutter widget has already connected itself to core.
=> refactor: cleanup connections in MainWindow

src/napari_micromanager/_gui_objects/_mda_widget.py, src/napari_micromanager/_gui_objects/_sample_explorer_widget.py, src/napari_micromanager/_mda_meta.py, src/napari_micromanager/main_window.py, tests/conftest.py, tests/test_multid_widget.py
this adds a new `mda_sequence` fixture in conftest that should be used when we want to test something (such as MDA acquisition) across a handful of MDAs.
Note, I can't update the explorer widget in this PR since it's widget doesn't have a `set_state` method.... will do in a followup
cc @fdrgsp ... you could use this fixture in #225 to get a handful of MDA sequence objects
=> test: add `mda_sequence` parametrized fixture

src/napari_micromanager/main_window.py, tests/conftest.py, tests/test_layer_scale.py, tests/test_multid_widget.py
This PR adds a `layer.scale` info to all the image layers acquire through `napari-micromanager` (mda, explorer, preview).
=> feat: add scale to layers

pyproject.toml, src/napari_micromanager/_gui_objects/_illumination_widget.py, src/napari_micromanager/_util.py
Will use https://github.com/pymmcore-plus/pymmcore-widgets/pull/90 in place of the Illumination widget.
This will fail until v0.2.1 of widgets is released
=> refactor: use properties widget from pymmcore-widgets for illum widget

src/napari_micromanager/_mda_handler.py, src/napari_micromanager/main_window.py, tests/test_layer_scale.py
trying to isolate the parts of the main window that just mediate events between the core and napari (but which aren't a widget)
=> refactor: pull out mda handling logic into MDAHandler object

src/napari_micromanager/_gui_objects/_min_max_widget.py, src/napari_micromanager/main_window.py
puts the logic for updating minmax on the minmax widget itself, removing it from the main window.  Also simplifies the layout down to a couple lines
=> refactor: pull minmax logic off main window, and reduce minmax widget layout logic

tests/test_explorer.py
I'm adding tests for napari-micromanager in pymmcore-widgets, and this failure popped up because we were importing private stuff from pymmcore-widgets here.
https://github.com/pymmcore-plus/pymmcore-widgets/actions/runs/3648433889/jobs/6161851543
just a reminder that even if the other library is our own library, you still want to be careful about importing and using private modules.  private implies that the library could change it without warning (and not worry about breaking any downstream library)
=> fix: remove private import from pymmcore-widgets

src/napari_micromanager/_mda_handler.py, src/napari_micromanager/_mda_meta.py, tests/test_multid_widget.py
continueing in the simplification/dedup of the MDAHandler logic.  this unifies the `on_mda_frame` behavior.    It adds a new  stateless `_id_idx_layer` function that takes an event object and returns the info needed to get the appropriate zarr array, the index in the array at which the event image belongs, and teh name of the corresponding layer in the viewer.
=> refactor: simplify on-frame logic

pyproject.toml
Deals with this error:
```
ImportError while loading conftest '/home/ian/Documents/oss/micro/napari-micromanager/tests/conftest.py'.
tests/conftest.py:6: in <module>
from napari_micromanager._mda_meta import SEQUENCE_META_KEY, SequenceMeta
src/napari_micromanager/__init__.py:9: in <module>
from .main_window import MainWindow
src/napari_micromanager/main_window.py:15: in <module>
from ._mda_handler import _NapariMDAHandler
src/napari_micromanager/_mda_handler.py:11: in <module>
from napari.experimental import link_layers, unlink_layers
/home/ian/mambaforge/envs/micro-control-dev/lib/python3.10/site-packages/napari/experimental/__init__.py:1: in <module>
from ..components.experimental.chunk import chunk_loader, synchronous_loading
/home/ian/mambaforge/envs/micro-control-dev/lib/python3.10/si …
```
=> Fix test error from skimage warning

src/napari_micromanager/_gui_objects/_mda_widget.py
Prior to this change the MDA widget would not launch due to a menagerie of naming errors.
This includes part of the changes from #237, but not the changes to the explorer tests.
attn: @JasonYu1 and @fdrgsp
=> Fix: Update mda for new pymmcore-widgets

pyproject.toml, src/napari_micromanager/_gui_objects/_sample_explorer_widget.py, src/napari_micromanager/_saving.py, tests/conftest.py, tests/test_explorer.py, tests/test_main_window.py, tests/test_multid_widget.py
pins widgets to >0.3.0 and gets tests passing again.
Note @fdrgsp  ... I'm just skipping the sample explorer tests here.  Please fix those when you get a chance
=> fix: add fixes for new widgets

pyproject.toml, src/napari_micromanager/_mda_handler.py, src/napari_micromanager/main_window.py, tests/test_layer_scale.py
If the user doesn't set the resolution in their config then we can an error in vispy
```
File "C:\Users\TE-2000\mambaforge\envs\micro-control-fresh\lib\site-packages\numpy\linalg\linalg.py", line 89, 
in _raise_linalgerror_singular 
raise LinAlgError("Singular matrix")                                                                                                                                                           numpy.linalg.LinAlgError: Singular matrix   
```
This protects against that and adds a test - based on #243 in order to have tests semi functional
=> fix: Prevent crash when pixelSize = 0

src/napari_micromanager/_gui_objects/_toolbar.py
Fix:
- when opening the widgets for the first time, the `napari` `QDockWidget` option `_close_button=False` didn't have any effect and the close button was still there. This fixes the problem (see images below).
- make the `PropertyBrowser` a floating dockwidget instead of automatically docking it when opened (see images below).
- add a toolbar second line since everything is becoming too packed in one line (mostly when a user will have more that the two shutters that we use in test config) (see images below)
---
---
=> fix: fix _close_btn + add toolbar new line + propbrowser floating

src/napari_micromanager/main_window.py
closes #241
@ianhi, this is sufficient to get rid of that warning (I can explain offline why).  all the other stuff there, including the recursion error, is indeed just napari not yet supporting python 3.11
=> fix: fix warning on private access

src/napari_micromanager/_mda_handler.py, tests/test_layer_scale.py
Follow up to #244 in which I fixed one bug, but introduced another
=> fix: don't leave scale undefined

launch-dev.py, src/napari_micromanager/_mda_handler.py, src/napari_micromanager/_mda_meta.py, src/napari_micromanager/_saving.py
This PR removes unused old explorer widget stuff.
=> fix: remove explorer stuff

src/napari_micromanager/_gui_objects/_illumination_widget.py
This PR adds a `QSizePolicy` to the `IlluminationWidget`.
___
=> fix: minor fix IlluminationWidget

tests/test_multid_widget.py
this changes the way one of the tests works (rather than manually emitting just the right signals, it just runs the mda)
=> test: change main_window_mda test

pyproject.toml
This bumps the superqt dependency to take advantage of https://github.com/pyapp-kit/superqt/pull/185, which is necessary for https://github.com/pymmcore-plus/pymmcore-plus/pull/246 to work without breaking napari-micro
=> build: bump superqt

pyproject.toml, src/napari_micromanager/_gui_objects/_mda_widget.py, src/napari_micromanager/_gui_objects/_toolbar.py, src/napari_micromanager/main_window.py
This refactors `_toolbar` to get rid of a lot of boilerplate and make it clearer what's going on.
However, some styles have been lost in the process (though I think those styles were a bit too "manually-curated" and specific).  So this will need a little work together with @fdrgsp to get back to a nice looking place.  I think we should do away with the group boxes, which are presumably only being used for the border (which could be added as a style to the toolbar, etc...)
fixes #255
=> refactor: changing toolbar structure

src/napari_micromanager/_gui_objects/_toolbar.py
This is related to #288 
merge after https://github.com/pymmcore-plus/pymmcore-widgets/pull/196
In this PR we are removing the `ObjectivesToolBar` `_resize_obj()` method and we moved it directly to `pymmocre-widgets`  `ObjectivesWidget()` (https://github.com/pymmcore-plus/pymmcore-widgets/pull/196). This should fix the issue found in #288  since resizing is performed directly when the combo is created.
closes #288.
=> fix: ObjectivesToolBar

tests/test_layer_scale.py
fixes an issue seen on pyside2 after recent pymmcore/widgets updates
=> fix: don't use global instance in layer_scale test

src/napari_micromanager/_core_link.py, src/napari_micromanager/main_window.py, tests/test_layer_scale.py, tests/test_main_window.py
This abstracts the logic that links events from a viewer to a new/smaller `CoreViewerLink` object.
(the main window now composes one of these objects).
The goal is to keep a little better separation of concerns.  and make it clearer how you could conceptually link different viewers to different cores (even if that's rare)
=> refactor: Refactor out logic linking core events to viewer events from the MainWindow

.pre-commit-config.yaml, README.md, pyproject.toml, src/napari_micromanager/_gui_objects/_toolbar.py
this PR adds the name `mmcore` to the console in napari once the plugin has been activated, so you no longer need to grab `mmcore = CMMCorePlus.instance()`, you can immediately use `mmcore`, as well as `MDASequence` and `MDAEvent`
cc @linshaova ... this would make your usage slightly easier
closes #253
=> feat: add `mmcore` to viewer console namespace

README.md, src/napari_micromanager/_mda_handler.py
To set the zarr dtype, use `getBytesPerPixel`  instead of  `getImageBitDepth` but get this info from using `getBytesPerPixel` 
closes #295
=> fix: fix zarr dtype

src/napari_micromanager/_mda_handler.py
this makes it so that even if napari-micromanager didn't start the MDA, any MDA running in the currently monitored CMMCorePlus instance will be shown in the viewer.  Closes #305 
There are still places where bugs could potentially happen if frameReady somehow got emitted without sequenceStarted being emitted (not sure how that would happen), but those latent bugs have always been there
=> Show output from any pymmcore-plus MDA in napari viewer

tests/test_multid_widget.py
this fixes a small issue in one of the tests.  Not sure why it hasn't been failing on ci:
the `MDASequence.replace()` method will serialize all objects, including metadata... meaning it may turn a `SequenceMeta()` object into a dict... that's a broader issue that needs examining, but this is just a local workaround
=> test: small fix to test

src/napari_micromanager/_gui_objects/_mda_widget.py, tests/test_multid_widget.py
fix `SequenceMeta` /`dict` error in tests not passing both locally and in in #309: `FAILED tests/test_multid_widget.py::test_saving_mda[splitC-nT=0-nZ=0-nC=1] - AttributeError: 'dict' object has no attribute 'split_channels'
`
note: new test added
=> fix: fix error when loading SequenceMeta as dict

src/napari_micromanager/_core_link.py, src/napari_micromanager/_mda_handler.py, tests/test_main_window.py
Necessary after https://github.com/pymmcore-plus/pymmcore-plus/pull/314
- use the new core.events.imageSnapped
- when a MDA is running, we don't want to update the image preview layer (since we're already updating the active experiment layers)
- add test
=> fix: prevent preview update when mda is running

src/napari_micromanager/__main__.py
currently if we try to run 
`napari-micromanager -c "test_config.cfg"` (or `python -m napari_micromanager`) 
we get an `unrecognized arguments` error.
I think it's because the `main()` function in `__main__.py` is considering `.../napari-micromanager/src/napari_micromanager` (or `.../napari-micromanager/src/napari_micromanager__main__.py` as the first argument.  
This PR fixes that issue.
=> fix: fix when passing a config file in the command line

.github/workflows/test.yml, pyproject.toml
This takes advantage of the new `mmcore build-dev` command https://github.com/pymmcore-plus/pymmcore-plus/pull/331 and caches the result for faster ci
=> ci: use `mmcore build-dev` for linux, cache result

src/napari_micromanager/_core_link.py
fixes issue with shutter not re-opening
=> fix: shutter re-opening after changing config during live mode
